export const ROLE_HOLIDAY_MANAGER = "HOLIDAY_MANAGER";

export const RESPONSIBILITY_WORKLOG_MANAGEMENT = "WORKLOG_MANAGEMENT";
export const RESPONSIBILITY_SHIFT_MANAGEMENT = "SHIFT_MANAGEMENT";
export const RESPONSIBILITY_HOLIDAY_MANAGEMENT = "HOLIDAY_MANAGEMENT";
export const RESPONSIBILITY_WORKSHEET_MANAGEMENT = "WORKSHEET_MANAGEMENT";
export const RESPONSIBILITY_ANNOUNCEMENT_MANAGEMENT = "ANNOUNCEMENT_MANAGEMENT";
export const RESPONSIBILITY_ANNOUNCEMENT_SMS = "ANNOUNCEMENT_SMS";
export const RESPONSIBILITY_RESERVATION_MANAGEMENT = "RESERVATION_MANAGEMENT";

export const ACL_HOLIDAY_APPROVE = "ACL_HOLIDAY_APPROVE";
export const ACL_OWN_HOLIDAY_APPROVE = "ACL_OWN_HOLIDAY_APPROVE";
export const ACL_EDIT_PERSON = "ACL_EDIT_PERSON";
export const ACL_EDIT_ANNOUNCEMENT = "ACL_EDIT_ANNOUNCEMENT";
export const ACL_SEND_SMS_ANNOUNCEMENT = "ACL_SEND_SMS_ANNOUNCEMENT";
export const ACL_EDIT_LOCKED_WORKLOGS = "ACL_EDIT_LOCKED_WORKLOGS";
export const ACL_EDIT_LOCKED_ATTENDANCES = "ACL_EDIT_LOCKED_ATTENDANCES";
export const ACL_RESERVATION_APPROVE = "ACL_RESERVATION_APPROVE";
export const ACL_CREATE_SERVICE_RESERVATION = "ACL_CREATE_SERVICE_RESERVATION";
export const ACL_EDIT_RESERVATION = "ACL_EDIT_RESERVATION";

export const MODULE_PERSONS = "persons";
export const MODULE_EDOS = "edos";
export const MODULE_ANNOUNCEMENTS = "announcements";
export const MODULE_RESERVATIONS = "reservations";

//shodné pojmenování s názvem tříd
export const RESERVATION_VEHICLE = "Vehicle";
export const RESERVATION_ROOM = "Room";
export const RESERVATION_APARTMENT = "Apartment";
export const RESERVATION_MEASURING_EQUIPMENT = "MeasuringEquipment";
export const RESERVATION_IT_DEVICE = "ITDevice";
